- hosts: all
  vars_files:
    - defaults/main.yml
    - vars/main.yml
  tasks:
    - include: tasks/main.yml
      influxdb_cluster_servers: yes
      influxdb_overwrite_hosts_file: yes
  handlers:
    - include: handlers/main.yml
