---
- name: Update hosts configuration
  template: 
    src: etc/hosts.j2
    dest: /etc/hosts
    force: yes
    backup: yes
    owner: root
    group: root
    mode: 0644
  when: influxdb_overwrite_hosts_file

- name: Set clustered configuration
  template:
    src: etc/default/influxdb.j2
    dest: /etc/default/influxdb
    force: yes
    backup: yes
    owner: root
    group: root
    mode: 0644
  register: influxdb_cluster_set

- name: Purge existing peer data
  file: 
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ influxdb_meta_dir }}/id"
    - "{{ influxdb_meta_dir }}/raft.db"
    - "{{ influxdb_meta_dir }}/peers.json"
  when: influxdb_cluster_set.changed or influxdb_purge_peer_data

- name: Restart InfluxDB
  service: 
    name: influxdb
    state: restarted
  when: influxdb_cluster_set.changed or influxdb_purge_peer_data

- name: Pause for a moment
  pause:
    seconds: 5
  when: influxdb_cluster_set.changed or influxdb_purge_peer_data
  
- name: Collect cluster status
  command: "{{ influxdb_binary_path }}/influx -execute 'show servers'"
  register: influxdb_show_servers_output

- name: Assert clustering status (local/vagrant)
  assert:
    that:
      - "influxdb_show_servers_output.stdout.find(item)"
  with_items: groups['all']
  when: is_vagrant

- name: Assert clustering status (non-local)
  assert:
    that:
      - "influxdb_show_servers_output.stdout.find(item)"
  with_items: groups['influxdb']|default([], True)
  when: "'influxdb' in groups and is_vagrant == False"
  