---
- name: Check to see which databases already exist
  command: "{{ influxdb_binary_path }}/influx -execute 'show databases'"
  register: db_listing
  changed_when: no

- name: Create demo database
  command: "{{ influxdb_binary_path }}/influx -execute 'CREATE DATABASE {{ influxdb_sample_database_name }}'"
  when: db_listing.stdout.find("{{ influxdb_sample_database_name }}") == -1

- name: Load demo data
  uri:
    url: http://{{ influxdb_meta_hostname }}:{{ influxdb_http_port }}/write?db={{ influxdb_sample_database_name }}
    method: POST
    body: "{{ influxdb_sample_measurement_name }},host=server_{{ 10 | random }},az=US{{ 5 | random }} value={{ 100 | random }}"
    status_code: 204
  with_sequence: start=1 end=10


