---
- name: Update hosts configuration
  template: 
    src: etc/hosts.j2
    dest: /etc/hosts
    force: yes
    backup: yes
    owner: root
    group: root
    mode: 0644
  when: influxdb_overwrite_hosts_file

- include: install-redhat.yml
  when: ansible_os_family == "RedHat"

- include: install-debian.yml
  when: ansible_os_family == "Debian"