- name: Install any necessary dependencies [Debian/Ubuntu]
  apt: 
    name: "{{ item }}" 
    state: present 
    update_cache: yes 
    cache_valid_time: 3600

  with_items:
    - python-httplib2
    - python-apt
    - curl

- name: Import InfluxDB GPG signing key [Debian/Ubuntu]
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present

- name: Add InfluxDB repository [Debian/Ubuntu]
  apt_repository:
    repo: deb https://repos.influxdata.com/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ install_version }}
    state: present
    

- name: Install InfluxDB packages [Debian/Ubuntu]
  apt: 
    name: influxdb
    state: present