- name: Install any necessary dependencies [RedHat/CentOS]
  yum: 
    name: "{{ item }}" 
    state: present
  with_items:
    - curl

- name: Add InfluxDB repository file [RHEL/CentOS]
  template:
    src: etc/yum.repos.d/influxdb.repo.j2
    dest: /etc/yum.repos.d/influxdb.repo
    force: yes
    backup: yes

- name: Install InfluxDB packages [RHEL/CentOS]
  yum: 
    name: influxdb
    state: present
