---
- name: Update hosts configuration
  template: 
    src: etc/hosts.j2
    dest: /etc/hosts
    force: yes
    backup: yes
    owner: root
    group: root
    mode: 0644
  when: influxdb_overwrite_hosts_file

- include: install-redhat.yml
  when: ansible_os_family == "RedHat"

- include: install-debian.yml
  when: ansible_os_family == "Debian"

- name: Capture InfluxDB version information
  command: influxd version
  register: influxdb_runtime_version_raw

- name: Capture InfluxDB version, branch, and commit
  set_fact:
    influxdb_runtime_version: "{{ influxdb_runtime_version_raw.stdout.split()[1] }}"
    influxdb_runtime_branch: "{{ influxdb_runtime_version_raw.stdout.split()[3] }}"
    influxdb_runtime_commit: "{{ influxdb_runtime_version_raw.stdout.split()[4] }}"
