---
- name: Install any necessary dependencies [RedHat/CentOS]
  yum: 
    name: "{{ item }}" 
    state: present
  with_items:
    - curl

- name: Add InfluxDB repository file [RHEL/CentOS]
  template:
    src: etc/yum.repos.d/influxdb.repo.j2
    dest: /etc/yum.repos.d/influxdb.repo
    force: yes
    backup: yes
  when: influxdb_install_url is not defined or influxdb_install_url == None

- name: Install InfluxDB packages [RHEL/CentOS]
  yum: 
    name: influxdb
    state: present
  when: influxdb_install_url is not defined or influxdb_install_url == None

- name: Install InfluxDB from URL [RHEL/CentOS]
  yum: 
    name: "{{ influxdb_install_url }}"
    state: present
  when: influxdb_install_url is defined and influxdb_install_url != None
  