---
- include: install.yml
  tags: [influxdb, install]

- include: configure.yml
  tags: [influxdb, configure]

- name: Start the InfluxDB service
  service:
    name: influxdb
    state: restarted
    enabled: yes
  register: influxdb_started
  when: influxdb_start_service

- name: Wait for InfluxDB to come up
  wait_for:
    host: "{{ influxdb_bind_hostname }}"
    port: "{{ influxdb_http_port }}"
    delay: 5
    timeout: 30
  when: influxdb_started.changed and influxdb_start_service
  
- include: demo.yml
  tags: [influxdb, demo]
  when: influxdb_load_sample_data and influxdb_http_auth_enabled == "false" and influxdb_start_service

- include: verify.yml
  tags: [influxdb, verify]

- include: stress.yml
  tags: [influxdb, stress]
