---
- include: install.yml
  tags: [influxdb, install]

- include: configure.yml
  tags: [influxdb, configure]

- include: cluster.yml
  tags: [influxdb, cluster]
  when: influxdb_cluster_servers and influxdb_start_service

- include: demo.yml
  tags: [influxdb, demo]
  when: influxdb_load_sample_data and influxdb_http_auth_enabled == "false" and influxdb_start_service
